[config]
schemaVersion = "0.0.1"

[package]
namespace = "IHarbHD"
name = "DebugToolkit"
versionNumber = "3.17.0"
description = "Adds console command for debugging mods."
websiteUrl = "https://github.com/harbingerofme/DebugToolkit"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2117"
RiskofThunder-R2API_Core = "5.1.1"
RiskofThunder-R2API_ContentManagement = "1.0.6"
RiskofThunder-R2API_Networking = "1.0.2"
RiskofThunder-R2API_Prefab = "1.0.4"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./build"

[[build.copy]]
source = "../CHANGELOG.md"
target = "./"

[[build.copy]]
source = "../LICENSE"
target = "./"

[[build.copy]]
source = "../DebugToolkit.dll"
target = "./"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["mods", "tools"]